### ISSUE TITLE
Move to use uv for dependency management instead of poetry

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#329]
Some things to check to ensure [uv](https://astral.sh/uv) is compatible:

- [ ] ~Wait for GitHub's Dependabot supports uv (dependabot/dependabot-core#10040)~  -- [Renovate](https://docs.renovatebot.com) supports uv lock files and has an improved featureset over dependabot
- [x] Wait until uv can install from raw git repositories, E.g. https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/621502c54710a418ed1121ab997a763ae59718a2/pyproject.toml#L42 (https://docs.astral.sh/uv/concepts/dependencies#git)
- [x] Check pyproject.toml is valid in pre-commit hook (See astral-sh/uv#4264)
- [ ] ~Auto update semantic version in CI (astral-sh/uv#6298)~

**Comment by CarrotManMatt** [comment]
Having a version bump is no longer needed if we make use of https://github.com/ofek/hatch-vcs

**Comment by CarrotManMatt** [comment]
This relates to #164
